server:
#  配置端口
  port: 8089
#  配置数据源
spring:
  datasource:
    #如果存在多个数据源，监控的时候通过名字来区分开来
    name: mysql_springboot
    #使用Druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat
      driver-class-name: com.mysql.cj.jdbc.Driver
      #连接数据库的url
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true
      #连接数据库的账号
      username: root
      #连接数据库的密码
      password: 123456
      #初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
      initial-size: 1
      #最小连接池数量
      min-idle: 1
      #最大连接池数量
      max-active: 20
      #获取连接池最大等待时间，单位毫秒
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      #连接保持空闲而不被驱逐的最长时间
      min-evictable-idle-time-millis: 300000
      #用来检测连接是否是有效的SQL，要求是一个查询语句
      validation-query: SELECT 'x'
      #申请连接的时候检测，如果空闲时间大于time-between-eviction-runs-millis,执行validation检测连接是否有效
      test-while-idle: true
      #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      test-on-borrow: false
      #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      test-on-return: false
      #是否缓存preparedStatement,即PSCache
      pool-prepared-statements: false
      #要启用PSCache，必须配置大于0，当大于0时，pool-prepared-statements自动触发修改为true
      max-pool-prepared-statement-per-connection-size: 20

mybatis:
    #mapper.xml包地址
    mapper-locations: classpath:/mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
    #javaBean类的地址
    type-aliases-package: com.example.springboottest.entity  # 注意：对应实体类的路径

#pagehelper分页插件
pagehelper:
  #数据库的方言
  helper-dialect: mysql
  #启用合理化，如果pageNum < 1会查询第一页，如果pageNum > pages会查询最后一页
  reasonable: true
  support-methods-arguments: true
  params: count=countSql


